vrf: Handle busy failures on cgroup delete
testifreload.py:Testdhcp_relay_vrf smoke test is hitting a race where
attempts to delete the cgroup are failing with the EBUSY. This appears
to be a transient error so just try again 1 second later, repeating
up to 5 times before giving up.

Ticket: CM-11003
Review: Roopa
Testing: cl-tests/tests/smoke/testifreload.py:Testdhcp_relay_vrf

Signed-off-by: David Ahern <dsa@cumulusnetworks.com>
Acked-by: Roopa Prabhu <roopa@cumulusnetworks.com>

diff --git a/bin/vrf b/bin/vrf
--- a/bin/vrf
+++ b/bin/vrf
@@ -187,7 +187,15 @@ function vrf_configure_cgroup
 function vrf_delete_cgroup
 {
 	log_cmd "cgdelete -g l3mdev:/${1}"
-	cgdelete -g l3mdev:/${1}
+
+	# handle transient EBUSY error by trying again
+	for n in $(seq 1 5); do
+		cgdelete -g l3mdev:/${1}
+		[ $? -eq 0 ] && return 0
+		sleep 1
+	done
+
+	return 1
 }
 
 ################################################################################
@@ -400,6 +408,12 @@ function vrf_teardown
 	fi
 
 	vrf_delete_cgroup ${vrf}
+	if [ $? -ne 0 ]; then
+		echo "Failed to delete cgroup for vrf ${vrf}"
+		return 1
+	fi
+
+	return 0
 }
 
 function vrf_list
