vrf: Fix checking of special characters in vrf name
get_vrf_arg is used to santize user input and only allow specific
characters. Use of '-' in the name is tripping up this check in
some cases (vci images). Enhance the character list to make it
clear that the character '-' is allowed.

Signed-off-by: David Ahern <dsa@cumulusnetworks.com>
[ commit 209b2b4f36e6 from CL repo ]

diff --git a/bin/vrf b/bin/vrf
--- a/bin/vrf
+++ b/bin/vrf
@@ -56,9 +56,9 @@ function get_vrf_arg
 {
 	local vrf
 
-	vrf="${1//[^a-zA-Z0-9_-.]/}"
+	vrf="${1//[^a-zA-Z0-9_.\-]/}"
 	if [ "$vrf" != "$1" ]; then
-		echo "Invalid VRF" >&2
+		echo "Invalid VRF name" >&2
 		return 1
 	fi
 
