vrf: Cleanup error messages for task exec
cgtools is a dependency for cumulus-vrf so cgexec will exist.
Furthermore, hide the error message from cgexec as users do not
need to know the details of how the task association for VRFs
is implemented.

Signed-off-by: David Ahern <dsa@cumulusnetworks.com>

diff --git a/cumulus-bin/vrf b/cumulus-bin/vrf
--- a/cumulus-bin/vrf
+++ b/cumulus-bin/vrf
@@ -706,17 +706,18 @@ function task_exec
 		return 1
 	fi
 
-	which cgexec >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		echo "cgexec not found. cgroups tools installed?"
-		return 1
+	if [ "$vrf" = "default" ]; then
+		cgexec -g l3mdev:/ $* 2>/dev/null
+		rc=$?
+	else
+		cgexec -g l3mdev:${vrf} $* 2>/dev/null
+		rc=$?
 	fi
 
-	if [ "$vrf" = "default" ]; then
-		cgexec -g l3mdev:/ $*
-	else
-		cgexec -g l3mdev:${vrf} $*
+	if [ $rc -ne 0 ]; then
+		echo "Failed to run command in VRF context."
 	fi
+	return $rc
 }
 
 function task_cmd
