systemd: Make systemd service file vrf based
Rather than use mgmt-vrf.service as a template that gets modified
leverage systemd's @ infrastructure. vrf@.service is the template
and then instances are vrf@<vrf>.service with %I passed as the arg
to scripts.  This change significantly simplifies the systemd service
handling.

In the process relax the constraint that only management VRF is
supported (needed for dhcrelay and dhcpd) and the check whether
the service is running/enabled in default VRF. This has shown to
be overly restrictive.

Signed-off-by: David Ahern <dsa@cumulusnetworks.com>

diff --git a/cumulus-bin/vrf b/cumulus-bin/vrf
--- a/cumulus-bin/vrf
+++ b/cumulus-bin/vrf
@@ -17,7 +17,6 @@ MGMT_VRF=mgmt
 
 SYSTEMD_DIR=/lib/systemd/system
 SYSTEMD_USER=/etc/systemd/user
-MGMT_VRF_SERVICE=${SYSTEMD_DIR}/mgmt-vrf.service
 CFGDIR=/var/lib/cumulus-vrf
 
 ################################################################################
@@ -778,11 +777,6 @@ function valid_vrf
 		return 1
 	fi
 
-	if [ "$vrf" != "$MGMT_VRF" ]; then
-		echo "This command is currently limited to management VRF."
-		return 1
-	fi
-
 	return 0
 }
 
@@ -792,35 +786,14 @@ function valid_vrf
 function systemd_enable_vrf
 {
 	local vrf=$1
-	local f
 
-	vrf_exists $vrf
-	if [ $? -ne 0 ]; then
-		echo "VRF does not exist"
-		return 1
-	fi
+	systemctl enable vrf@${vrf}.service
+	systemctl start  vrf@${vrf}.service
 
-	# convert VRF name to systemd service name
-	# - want to include "vrf" in the service name
-
-	name=$(normalize_vrf_name $vrf)
-	if [ $? -ne 0 ]; then
-		echo "Invalid VRF"
-		return 1
-	fi
-
-	#
-	# create systemd service file for VRF
-	#
-	f=${SYSTEMD_DIR}/${name}.service
-	if [ ! -e $f ]; then
-		cp $MGMT_VRF_SERVICE $f
-		sed -ie "s/start-systemd-vrf mgmt/start-systemd-vrf $vrf/" $f
-		sed -ie "s/Description=Management VRF/Description=VRF $vrf/" $f
-	fi
-
-	systemctl enable ${name}.service
-	systemctl start  ${name}.service
+	# if we actually start systemd it takes a bit for it to
+	# initialize and be ready to start services; moving too
+	# fast and the service startup fails.
+	sleep 2
 }
 
 #
@@ -829,30 +802,10 @@ function systemd_enable_vrf
 function systemd_disable_vrf
 {
 	local vrf=$1
-	local f
 
-	# do not check existence of vrf device; it can be deleted before
-	# process shutdown
-
-	name=$(normalize_vrf_name $vrf)
-	if [ $? -ne 0 ]; then
-		echo "Invalid VRF"
-		return 1
-	fi
-
-	f=${SYSTEMD_DIR}/${name}.service
-	[ ! -f ${f} ] && return 0
-
-	systemctl stop ${name}.service
+	systemctl stop vrf@${vrf}.service
 	rc=$?
-	systemctl disable ${name}.service
-
-	#
-	# remove systemd service file except for mgmt vrf
-	#
-	if [ "$f" != "$MGMT_VRF_SERVICE" ]; then
-		rm -f $f
-	fi
+	systemctl disable vrf@${vrf}.service
 
 	return $rc
 }
@@ -896,24 +849,20 @@ function rm_service_onboot
 	mv ${cfg}.new ${cfg}
 }
 
-#
-# See if a service is running in the default VRF context. If so
-# attempts to start service in other VRF will fail.
-#
-function check_default_vrf
+function systemd_symlink
 {
-	local service=$1
+	local vrf=$1
+	local service=$2
 
-	systemctl -n 0 status ${service}.service 2>/dev/null | egrep -q 'Active.*running'
-	if [ $? -eq 0 ]; then
-		echo "Service is currently running in default VRF."
-		return 1
-	fi
+	systemd_file=${SYSTEMD_DIR}/${service}.service
+	user_file=${SYSTEMD_USER}/${service}.service
 
-	systemctl -n 0 status ${service}.service 2>/dev/null | egrep -q 'Loaded.*enabled'
-	if [ $? -eq 0 ]; then
-		echo "Service is currently enabled in default VRF."
-		return 1
+	if [ ! -e ${user_file} ]; then
+		if [ ! -f ${systemd_file} ]; then
+			echo "systemd service file not found."
+			return 1
+		fi
+		ln -s ${systemd_file} ${user_file}
 	fi
 
 	return 0
@@ -950,25 +899,13 @@ function service_start
 		return 1
 	fi
 
-	#
-	# is this service running in default context?
-	#
-	check_default_vrf $service || return 1
-
 	# make sure systemd in VRF is enabled
 	systemd_enable_vrf $vrf
 	[ $? -ne 0 ] && return 1
 
-	#
 	# create symlink for service to user directory
-	#
-	if [ ! -e ${SYSTEMD_USER}/${service}.service ]; then
-		if [ ! -f ${SYSTEMD_DIR}/${service}.service ]; then
-			echo "systemd service file not found."
-			return 1
-		fi
-		ln -s ${SYSTEMD_DIR}/${service}.service ${SYSTEMD_USER}
-	fi
+	systemd_symlink $vrf $service
+	[ $? -ne 0 ] && return 1
 
 	if [ "$onboot" = "yes" ]; then
 		add_service_onboot ${vrf} ${service}
