packaging: Revert install of alternatives
Installing the alternatives for ping and traceroute is causing test
scripts to break as the name of ping changed. Revert the install of
the wrappers.

This change also includes a short term hack to revert the alternatives
on an upgrade. Will remove this code in a few days.

Ticket: CM-9977

Signed-off-by: David Ahern <dsa@cumulusnetworks.com>

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -70,6 +70,33 @@ install_alt() {
     fi
 }
 
+uninstall_alt() {
+
+    # Example invocations of the routine:
+    #  uninstall_alt tail /usr/lib/cumulus/tail.cl /usr/bin/tail /usr/bin/tail.coreutils
+
+    local altname=$1
+    local altpath=$2
+    local origpath=$3
+    local origaltpath=$4
+
+    echo "unstalling alternative $altpath for $altname .. "
+    update-alternatives --remove $altname $altpath
+    if [ $? -ne 0 ]; then
+	    echo "failed to uninstall alternative $altname $altpath"
+	    return 1
+    fi
+
+    echo "unstalling alternative $origaltpath for $altname .. "
+    update-alternatives --remove $altname $origaltpath
+    if [ $? -ne 0 ]; then
+	    echo "failed to uninstall alternative $altname $origaltpath"
+	    return 1
+    fi
+
+    mv -f $origaltpath $origpath &>/dev/null
+}
+
 ARCH=`uname -m`
 ret=0
 
@@ -93,10 +120,10 @@ chmod 4755 /usr/lib/cumulus/traceroute.cl
 chmod 4755 /usr/lib/cumulus/traceroute6.cl
 
 # Install alternatives to ping and traceroute
-install_alt /bin/ping /usr/lib/cumulus/ping.cl
-install_alt /bin/ping6 /usr/lib/cumulus/ping6.cl
-install_alt /usr/bin/traceroute /usr/lib/cumulus/traceroute.cl
-install_alt /usr/bin/traceroute6 /usr/lib/cumulus/traceroute6.cl
+#install_alt /bin/ping /usr/lib/cumulus/ping.cl
+#install_alt /bin/ping6 /usr/lib/cumulus/ping6.cl
+#install_alt /usr/bin/traceroute /usr/lib/cumulus/traceroute.cl
+#install_alt /usr/bin/traceroute6 /usr/lib/cumulus/traceroute6.cl
 
 # We set PS1 in our profile.d script; remove the overrides by the
 # bash package
@@ -112,6 +139,32 @@ done
 if [ -f /home/cumulus/.bashrc ]; then
 	sed -ie 's/^PS1=/#PS1=/' /home/cumulus/.bashrc
 fi
+
+# short term hack to allow upgrades
+if [ -h /bin/ping ]; then
+	uninstall_alt ping  /usr/lib/cumulus/ping.cl  /bin/ping  /bin/ping.iputils-ping
+fi
+
+if [ -h /bin/ping6 ]; then
+	uninstall_alt ping6 /usr/lib/cumulus/ping6.cl /bin/ping6 /bin/ping6.iputils-ping
+fi
+
+if [ -h /etc/alternatives/traceroute ]; then
+	f=$(readlink /etc/alternatives/traceroute)
+	if [ "$f" = "/usr/lib/cumulus/traceroute.cl" ]; then
+		rm /etc/alternatives/traceroute
+		ln -s /usr/bin/traceroute.db /etc/alternatives/traceroute
+	fi
+fi
+
+if [ -h /etc/alternatives/traceroute6 ]; then
+	f=$(readlink /etc/alternatives/traceroute6)
+	if [ "$f" = "/usr/lib/cumulus/traceroute6.cl" ]; then
+		rm /etc/alternatives/traceroute6
+		ln -s /usr/bin/traceroute6.db /etc/alternatives/traceroute6
+	fi
+fi
+
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
